### ISSUE TITLE
Plugin config is invalid, continuing without plugins. Error: Invalid plugin config data type: <class 'list'>

### ISSUE THREAD

**Issue by guilhermedotcamargo** [Significant-Gravitas/Auto-GPT-Plugin-Template#23]
While running `docker compose run --rm auto-gpt --install-plugin-deps`, the following error appears:

`Plugin config is invalid, continuing without plugins. Error: Invalid plugin config data type: <class 'list'>`

My `plugins_config.yaml` file content is:

```yaml
commercetools:
  - config: {} # Configs from the plugin README and installation instructions.
  - enabled: true
```
---
When i remove the hyphen from the `plugins_config.yaml` file, the error does not appear anymore but the plugin is not loaded

**Comment by Annett-2601** [comment]
what settings should I use on the plugins_config.yaml file? 
```
AutoGPTSpacePlugin:
    config: {}
    enabled: true
```

or these
```
plugin_a:
  config:
    api_key: my-api-key
  enabled: false
PluginB:
  config: {}
  enabled: true 
```
If the latest settings are to be used, is it necessary to add a CHAT_ID for the telegram bot?
thanks.
